### ISSUE TITLE
Request examples not working

### ISSUE THREAD

**Issue by mehdikhrichfa** [TellMeFirst/tellmefirst#15]
Hi Giuseppe,

I'm working on the NoC Knowledge Platform and I am trying to use the TellMeFirst API. I tried generating a brand-new request as well as using the example you provided in the documentation, but I always get a timeout.
 ```
curl -F text=”The final work of legendary director Stanley Kubrick, who died within a week of 
completing the edit, is based upon a novel by Arthur Schnitzler.” -F numTopics=7 -F 
lang=english -F key=”” http://tellmefirst.polito.it:2222/rest/classify
 ```

**Comment by giuseppefutia** [comment]
It was a firewall issue. Now, it should work.
