### ISSUE TITLE
TMF APIs

### ISSUE THREAD

**Issue by marinadamato** [TellMeFirst/tellmefirst#25]
In the first example of the use of classify service for extracting topics from a PDF file, the last "-F" option, at the end of the command, is a redundancy that makes the command unable to work correctly. 

So the correct version of the command is:

`curl -F file=@/home/tellmefirst/files/2011-iscc-paper.pdf -F fileName="2011-iscc-paper.pdf" -F numTopics=7 -F lang=english http://tellmefirst.polito.it:2222/rest/classify`

**Comment by giuseppefutia** [comment]
Documentation updated
