### ISSUE TITLE
Max numTopics seems 7

### ISSUE THREAD

**Issue by alemela** [TellMeFirst/tellmefirst#8]
Using the API via curl and manually setting a number of topics higher than seven, TMF always returns max seven results. Instead using less than seven topics works.

**Comment by giuseppefutia** [comment]
I set a new threshold at 100. Try this: curl -F text="The final work of legendary director Stanley Kubrick, who died within a week of completing the edit, is based upon a novel by Arthur Schnitzler." -F numTopics=20 -F lang=english http://tellmefirst.polito.it:2222/rest/classify
